services:
  backend:
    image: gurpreetmahi/task-manager-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/taskdb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/tasks"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
  frontend:
    image: gurpreetmahi/task-manager-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
  db:
    image: postgres:15-alpine
    platform: linux/arm64
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskdb
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db-data: